target 'OnlyTa' do
  pod 'RongCloudIM/IMLib','~>2.8.30'
  pod 'RongCloudIM/IMKit','~>2.8.30'
  
  pod 'ReactiveCocoa'
  pod 'AFNetworking','~> 3.0.4'
  pod 'SVProgressHUD','~> 2.0.4'
  pod 'SDWebImage'
  pod 'MJRefresh'
  pod 'Qiniu'
  pod 'SDAutoLayout', '~> 2.1.3'
  pod 'AMapLocation'
end
